services:
  app:
    build: .
    command: sh -c "npm run migration:run && npm run start:prod"
    ports:
      - 3000:3000
    env_file:
      - .env.test
    depends_on:
      test_db:
        condition: service_healthy
      test_redis:
        condition: service_healthy
    environment:
      NODE_ENV: test
    networks:
      - test_network

  test_db:
    image: postgres:15
    restart: always
    env_file:
      - .env.test
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d weather_app_test"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - test_network

  test_redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - test_network

volumes:
  pg_test_data:
  redis_test_data:

networks:
  test_network: