services:
  app:
    build: .
    command: sh -c "npm run migration:run && npm run start:prod"
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASS}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
