services:
  test_db:
    image: postgres:15
    restart: always
    ports:
      - ${TEST_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}
    volumes:
      - pg_test_data:/var/lib/postgresql/data

volumes:
  pg_test_data: