name: Unit, Integration & E2E Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # --- Unit Tests ---
      - name: Run unit tests
        run: npm run test

      # --- Integration Tests ---
      - name: Stop test database
        run: npm run test:integration:stop

      - name: Start test database
        run: npm run test:integration:start

      - name: Wait for DB to be ready
        run: npx wait-on tcp:5432

      - name: Run integration tests
        run: npm run test:integration
        env:
          DB_USER: test_user
          DB_PASS: test_pass
          DB_NAME: weather_app_test
          DB_HOST: localhost
          NODE_ENV: test

      - name: Stop test database
        run: npm run test:integration:stop

      # --- E2E Tests ---
      - name: Install Playwright and Browsers
        run: npx playwright install --with-deps

      - name: Start test database
        run: npm run test:e2e:start

      - name: Wait for DB to be ready
        run: npx wait-on tcp:5432

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          DB_USER: test_user
          DB_PASS: test_pass
          DB_NAME: weather_app_test
          DB_HOST: test_db
          NODE_ENV: test

      - name: Stop test database
        run: npm run test:e2e:stop
        